source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'bricks-Mantle_Example', :exclusive => true do
  pod "bricks-Mantle", :path => "../"
end

target 'bricks-Mantle_Tests', :exclusive => true do
  pod "bricks-Mantle", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
